.gitignore
puremagic/main.py
test/test_common_extensions.py

I'm in the process of making a few enhancements to the `puremagic` lib. One thing I thought was really helpful about the library is that it just looks at the first bytes and provides a standard name. I found that using when the alternative `libmagic`, the file types are just a long concatenated string and can make analysis based on those values to be somewhat difficult.
This commit just makes some of the code more legible and makes the magic numbers available via the result from the API.

Increase legibility and provide full magic info in results

---

puremagic/magic_data.json

Needed a pcapng signature. Official sig taken from here:
https://github.com/file/file/blob/ed02a943df27cb4130306f2c1e0ec4ba86aa04ab/magic/Magdir/sniffer#L297
Verified with a local pcapng file.

Adding pcapng signature

---

MANIFEST.in

I've submitted puremagic to the FreeBSD ports tree - see FreeBSD report https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258593
While generating the port, I noticed that the package distributed from PyPi is missing the test data files so the test suite will always fail if the source is fetched from there. The python test file (test_common_extensions.py) gets pulled into the python package because it has a .py extension, but the data files the tests run against are missed because they do not.
This commit grafts in test/ (pulls in everything) and then excludes pyc, pyo & pyd files per the recommended way of doing this in the python packaging manual.
FreeBSD preference is to pull all python packages from PyPi and to include test-suites where available. For right now, the options are either …

Include test files so test suite passes from PyPi

---

puremagic/main.py

I was facing this weird issue where downloading a previously uploaded PDF resulted in chrome complaining about not being able to open the document. Figured out what the actual issue was after comparing the original to the downloaded file which was missing the initial `%PDF-`. Manually resetting the stream worked but it would be nice to have puremagic do this automatically.

Reset stream cursor after read

---

puremagic/magic_data.json

Closes #48
Added .jxl filetypes per official specs at:
https://jpegxl.info/
https://github.com/libjxl/libjxl/blob/main/doc/format_overview.md
https://en.wikipedia.org/wiki/JPEG_XL
Raw test files `FF 0A`:  [jxl.zip](https://github.com/cdgriffith/puremagic/files/14383989/jxl.zip)
- JXL logo (Raw Data) extracted from [https://jpegxl.info/jxl-art.html](https://jpegxl.info/jxl-art.html)
- JXL logo (Exported from GIMP) as above but loaded and saved back out in GIMP
- kungfubaby convert from animated gif using [libjxl's cjxl](https://github.com/libjxl/libjxl/releases)
ISOBMFF test file `0000000c4a584c200d0a870a`:
I found one and only one so far (I spent a long time looking) at https://github.com/Exiv2/exiv2/issues/1503#issuecomment-803943178 big thanks 👏 to @kmilos for making one.

Update magic_data.json with .jxl

---

puremagic/magic_data.json

Closes #52 
JPEG XS Image and Video formats added. It's an odd format that seems to have a few variants and some conflicting info. Entries are derived from:
- https://www.loc.gov/preservation/digital/formats/fdd/fdd000545.shtml?loclr=blogsig
- https://en.wikipedia.org/wiki/JPEG_XS
- https://jpeg.org/jpegxs/
I've added some samples as well as the orignal AI prompt generated .jpg and .ppm file that will work with the reference software encoder (the docs say you can use raw as well but this seems too not be the case). The `.jxs` files included (which actually should be `.jxsc` according to the official specs) have slight variances in the header area from playing with different encoder settings, but the `0xff10ff50` remains a constant.
[JPEG XS …

Update magic_data.json with JPEG XS

---

puremagic/main.py

Closes #60 
Adds `encoding="utf-8"` to line 76 to resolve PYTHONWARNDEFAULTENCODING warning. Per the following:
- [https://peps.python.org/pep-0597/](https://peps.python.org/pep-0597/)
- [https://github.com/numpy/numpy/issues/24115](https://github.com/numpy/numpy/issues/24115)
It's something added in to Python 3.10 to help ensure text-based files are treated as UTF-8 for broader cross-platform compatibility. After Python 3.15 `encoding="utf-8"` will become the default, but leaving it in the code will not cause any issues.
Tested under windows by using `set PYTHONWARNDEFAULTENCODING=1` before running, no errors appeared so should all be good.

Update main.py to resolve PYTHONWARNDEFAULTENCODING

---

puremagic/magic_data.json
puremagic/main.py

Closes #57
While digging through files for PR #58 I discovered that we could do with a `footer` style reverse lookup on the multi part match to help boost confidence scores (especially if the footer is small as well). This modifies the multiple match to allow reverse looksup.
To behave like the normal forward match, we aggregate the `matched.byte_match` and `magic_row.byte_match` to provide a longer match to the `_confidence` function. One downside of the is that in the match data it will report the two matches smooshed together, e.g.:
- `.mlt` is `0x3c6d6c74` / `<mlt` (0.4) and `3c2f6d6c743e0a` / `</mlt>\n` (0,7), combined confidence of 0.8 but you'll see `<mlt</mlt>\n` in the data which looks untidy (could there be a better way to address this)
Also, some unexpected results:
- `.pt2` …

Multi part reverse lookup

---

puremagic/main.py

While adding #65 one of the things that flagged up was that no matter how long the `byte_match` the winner was not the longest match. This quick one liner addresses that issue. Confidence is sorted by `confidence` then `byte_match`.
Before, Alternate match 2 should be the winner:
```
China tax introduction(edited1).docx
Most likely match:
Format:        MS Office Open XML Format Document
Confidence:    80.0%
Extension:     .docx
MIME:          application/vnd.openxmlformats-officedocument.wordprocessingml.document
Offset:        0
Bytes Matched: b'PK\x03\x04\x14\x00\x06\x00'
Hex:           504b 0304 1400 0600
String:        PK
Alternate match #1
Format:        Microsoft Office 2007+ Open XML Format Document file
Confidence:    80.0%
Extension:     .xlsx
MIME: …
```

2024-05-06 Fix Confidence sorting

---

.github/workflows/tests.yml

The Python 3.13 release notes mention `puremagic` as one of the alternatives for `imghdr` which was removed from the Standard Library so let's ensure that its tests pass on Python 3.13 beta.
https://www.python.org/downloads/release/python-3130b1/
May raise `ModuleNotFoundError: No module named 'imghdr'` because Python 3.13 removes it from the Standard Library.
* https://docs.python.org/3/library/imghdr.html
> imghdr: use the projects [filetype](https://pypi.org/project/filetype/), [puremagic](https://pypi.org/project/puremagic/), or [python-magic](https://pypi.org/project/python-magic/) instead. (Contributed by Victor Stinner in [gh-104773](https://github.com/python/cpython/issues/104773).)
https://docs.python.org/3.13/whatsnew/3.13.html#pep-594-dead-batteries-and-other-module-removals

GitHub Actions: Test on Python 3.13 beta

---

puremagic/main.py

This allows Python 3.8 and 3.9 to use the streamlined type hint syntax of [PEP 563](https://peps.python.org/pep-0563/) and [PEP 649](https://peps.python.org/pep-0649/).
* https://docs.python.org/3/library/__future__.html#module-contents
% `ruff rule UP006 ` # https://docs.astral.sh/ruff/rules/non-pep585-annotation/
% `ruff rule UP007 ` # https://docs.astral.sh/ruff/rules/non-pep604-annotation/

Type hints: `from __future__ import annotations`

---

.github/workflows/tests.yml
puremagic/main.py
test/test_main.py

Closes #72
* #72
This might be more complete after #75 lands.
* #75
Current pytest results: `53 passed in 0.05s`
* `test_what_from_file` is 6 tests
* `test_what_from_file_none` is 1 test
* `test_what_from_string` is 38 tests
* `test_what_from_string_py311` is 2 tests
* Fail on `imghdr` only on Python < 3.11
* `test_what_from_string_todo` is 6 tests
* Fail on `puremagic`
@NebularNerd Your reviews, please.

For Python 3.13: A drop-in replacement for `imghdr.what()`

---

puremagic/magic_data.json
puremagic/main.py
test/test_common_extensions.py
test/test_main.py

```diff
- def what(file: os.PathLike | str | None, h: bytes | None) -> str | None:
+ def what(file: os.PathLike | str | None, h: bytes | None, imghdr_strict: bool = True) -> str | None:
```
> `imghdr_strict` enables bug-for-bug compatibility between `imghdr.what()` and `puremagic.what()` when the imghdr returns a match but puremagic returns None.  We believe that imghdr is delivering a "false positive" in each of these scenarios but we want `puremagic.what()`'s default behavior to match `imghdr.what()`'s false positives so we do not break existing applications.
> If `imghdr_strict is True` (the default) then a lookup will be done to deliver a matching result on all known false positives.  If `imghdr_strict is False` then puremagic's algorithms will determine the image type.  True is more …

Add a `imghdr_strict` option to `.what()` to deliver the same false positives

---

.pre-commit-config.yaml

https://docs.astral.sh/ruff
Also,
Remove __fix python encoding pragma (deprecated)__
% `pre-commit autoupdate`
% `pre-commit run --all-files`

Add ruff linter to pre-commit

---

.pre-commit-config.yaml
puremagic/__init__.py
puremagic/__main__.py
puremagic/main.py
scripts/parse_ftk_kessler_sigs.py
setup.py
test/test_common_extensions.py

* #71
Use `ruff check --select=C4,PERF,UP` to find and fix minor performance issues.  https://docs.astral.sh/ruff
% `ruff check --select=C4,PERF,UP --statistics | sort -k2`
```
1	C408   	[*] Unnecessary `list` call (rewrite as a literal)
1	PERF401	[ ] Use a list comprehension to create a transformed list
6	UP009  	[*] UTF-8 encoding declaration is unnecessary
2	UP015  	[*] Unnecessary open mode parameters
1	UP024  	[*] Replace aliased errors with `OSError`
5	UP030  	[*] Use implicit references for positional format fields
7	UP032  	[*] Use f-string instead of `format` call
```
% `ruff rule PERF401`
Derived from the **Perflint** linter.
Checks for `for` loops that can be replaced by a list comprehension.
When creating a transformed list from an existing list using a for-loop,
prefer a list …

Small performance improvements

---

.github/workflows/tests.yml
CHANGELOG.md
puremagic/main.py

- Changing to support Python 3.7 again

Version 1.25

---

setup.py

Fixes #89, by adding `py.typed` to `package_data`, this was validated by running locally the following commands:
```sh
$ pip wheel .
$ unzip -l puremagic-1.25-py3-none-any.whl
Archive:  puremagic-1.25-py3-none-any.whl
Length      Date    Time    Name
---------  ---------- -----   ----
102  07-05-2024 13:59   puremagic/__init__.py
90  07-05-2024 13:59   puremagic/__main__.py
143189  07-05-2024 13:59   puremagic/magic_data.json
15622  07-05-2024 13:59   puremagic/main.py
0  07-05-2024 13:59   puremagic/py.typed
1086  07-05-2024 14:02   puremagic-1.25.dist-info/LICENSE
5854  07-05-2024 14:02   puremagic-1.25.dist-info/METADATA
91  07-05-2024 14:02   puremagic-1.25.dist-info/WHEEL
10  07-05-2024 14:02   puremagic-1.25.dist-info/top_level.txt
775  07-05-2024 14:02 …
```

fix(dist): add py.typed to package_data

---

MANIFEST.in

Thanks for `puremagic`!
This continues #90 by ensuring `py.typed` is included in the sdist (it is not in the 1.26 tarball).

include py.typed in sdist

---

puremagic/magic_data.json

Hi! 
There is at least one system out in the wild that produces pdf files which start with a CRLF.
I added it as an extra entry.
Though from my testing, you can have any junk in front of the file as long as at some point you encounter the `%PDF-` string so a proper fix would be to look for the sequence of bytes/characters.
Anyways, stay safe out there!

Improve PDF file detection, fix description

---

puremagic/main.py

Closes #96
Closes #86
Puremagic is having trouble with super small files of less than 1k when opened as a stream, as the matches became better an issue has cropped up with `footer` matches trying to go into negative numbers. My previous PR #87 added a match for `.dmg` files which starts at -512 bytes from the end, which when the file is only a couple of hundred bytes made Puremagic very sad. 
This led to the errors shown in both the above issues, this fix adds a try/except into the stream logic, if the `max_foot` length exceeds the file size, then simply set it to the file size. I can't see there being an issue with this as it just results in `footer` being the whole file. While it could cause issues if you had a multi-GB file and some absurd even larger multi-GB negative match the …

2024-08-05 Tiny file fix and Confidence correction

---

puremagic/main.py

fsspec[gcsfs] throws an ValueError instead of a OSError

fix: fsspec compatibility

---

puremagic/main.py

Non regular files can not be trusted to be bounded. For example /dev/zero is infinitely large. Obtaining the footer of said file will never complete because file.seek() will never return. Instead it will fill up your memory until your process is targeted by the OOM killer.
Thanks for the package, very useful! However yesterday our production server got killed by the kernel's Out-Of-Memory killer. Turns out a database record referred to /dev/zero (where it should have been set to /dev/null).  Puremagic quickly ate all memory available on our server and then got shot in the face by OOM killer. ;-)
To reproduce on Linux: python3 -m puremagic /dev/zero
Thanks!

Halt on non-regular files like /dev/zero and /dev/random
